f2d/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

import follow.urls
import tracks.urls
import users.urls


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'f2d.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'f2d.views.homepage', name='homepage'),
    url(r'^d/', include(follow.urls)),
    url(r'^tracks/', include(tracks.urls)),
    url(r'^users/', include(users.urls)),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        (r'^media/(?P<path>.*)$',
         'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}))

tracks/urls.py
"""
    tracks.urls
    ~~~~~~~~~~~
    Django URL routes related to tracks.

    Copyright (C) 2015 FollowToDownload
"""
from django.conf.urls import patterns, url

from tracks import views


urlpatterns = patterns('',
    url(r'^upload', views.UploadView.as_view(), name='tracks.upload'),
    url(r'^info/(?P<track_id>.*)', views.InfoView.as_view(), name='tracks.info')
)

tracks/models.py
# -*- coding: utf-8 -*-
"""
    tracks.models
    ~~~~~~~~~~~~~
    Django models related to uploaded tracks.

    Copyright (C) 2015 FollowToDownload
"""
import uuid

from django.db import models

from tracks import entities
import users.models


class UploadedTrack(models.Model):
    """Represents an music track belonging to a user"""

    uploaded_track_id = models.AutoField(primary_key=True)
    track_url_id = models.CharField(
        max_length=36, blank=False, default=str(uuid.uuid4()), db_index=True
    )
    user = models.ForeignKey(users.models.SoundCloudUser, db_index=True)
    artist = models.CharField(max_length=256, blank=False)
    title = models.CharField(max_length=256, blank=False)
    track_file = models.FileField(blank=False)

    @property
    def downloads(self):
        """Compute and return the number of downloads for this track"""
        import follow.models
        return follow.models.TrackFollower.objects.filter(track=self)
    
    def as_entity(self):
        """Returns the entity form of the track.

        :rtype: tracks.entities.UploadedTrack
        """
        return entities.UploadedTrack(
            self.uploaded_track_id,
            self.track_url_id,
            self.user.id,
            self.artist,
            self.title,
            self.track_file
        )

    def __unicode__(self):
        """Returns the printed name for this entity

        :rtype: str or unicode
        """
        return u'(uploaded_track_id={}, user_id={})'.format(
            self.uploaded_track_id, self.user.pk
        )

tracks/forms.py
"""
    tracks.forms
    ~~~~~~~~~~~~
    Forms related to music tracks

    Copyright (C) 2015 FollowToDownload
"""
import logging

from django import forms
from django.conf import settings


logger = logging.getLogger(__name__)


class LimitedSizeFileField(forms.FileField):
    """A file field that raises an error if a maximum size is exceeded"""

    def __init__(self, *args, **kwargs):
        self.max_file_size_mb = kwargs.pop('max_file_size_mb')
        super(LimitedSizeFileField, self).__init__(*args, **kwargs)
    
    def clean(self, data, initial):
        max_file_size_bytes = (
            self.max_file_size_mb * 1E6
            if self.max_file_size_mb
            else None)
        if data and max_file_size_bytes and len(data) > max_file_size_bytes:
            raise forms.ValidationError(
                'File too large. Max size restricted to %r MB'
                % self.max_file_size_mb)
        return super(LimitedSizeFileField, self).clean(data, initial)


class UploadTrackForm(forms.Form):
    """Django form for for track file uploads"""

    artist = forms.CharField(max_length=256)
    title = forms.CharField(max_length=256)
    track_file = LimitedSizeFileField(
        max_file_size_mb=settings.MAX_TRACK_FILE_SIZE_MB,
        allow_empty_file=False)

tracks/views.py
"""
    tracks.views
    ~~~~~~~~~~~~
    Django views for tracks

    Copyright (C) 2015 FollowToDownload
"""
import logging

from django import shortcuts
from django.views import generic

from tracks import forms
from tracks import interactors
from tracks import models
import users.gateways


logger = logging.getLogger(__name__)


class UploadView(generic.TemplateView):
    """View for uploading a new track for the current user."""
    template_name = 'tracks/upload.html'

    def post(self, request, *args, **kwargs):
        soundcloud_user_id = request.session.get('soundcloud_user_id')

        if not soundcloud_user_id:
            return shortcuts.redirect('homepage')

        user = users.gateways.DjangoSoundCloudUserDataGateway.get_by_soundcloud_user_id(
            soundcloud_user_id
        )

        upload_form = forms.UploadTrackForm(request.POST, request.FILES)

        if upload_form.is_valid():
            uploaded_track = interactors.TrackUploadInteractor().run(
                user,
                **upload_form.cleaned_data
            )
            context = {
                'uploaded_track': uploaded_track
            }
            return shortcuts.render(
                request, 'tracks/upload_success.html', context
            )

        context = self.get_context_data(**kwargs)
        context['form'] = upload_form
        return shortcuts.render(request, 'tracks/upload.html', context)

    def get_context_data(self, **kwargs):
        context = super(UploadView, self).get_context_data(**kwargs)
        context['upload'] = True
        context['form'] = forms.UploadTrackForm()
        return context


class InfoView(generic.TemplateView):
    """View for seeing track info"""
    template_name = 'tracks/info.html'

    def get_context_data(self, **kwargs):
        context = super(InfoView, self).get_context_data(**kwargs)
        track_id = kwargs.get('track_id')
        context['track'] = models.UploadedTrack.objects.get(
            track_url_id=track_id
        )
        return context

tracks/templates/tracks/info.html
{% extends "dashboard_base.html" %}

{% block content %}
<h1>{{ track.artist }} - {{ track.title }}</h1>
<p>
When a user follows you they get their free download from:
</p>
<p>
<a target="_blank" href="{{ track.track_url }}">{{ track.track_url}}</a>
</p>
<h3>
Your follow2download URL for this track:
</h3>
<pre>http://follow2download.com/d/{{ track.track_url_id }}</pre>
<div>
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-9844785619338228"
     data-ad-slot="8268335793"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
{% endblock %}

tracks/templates/tracks/upload.html
{% extends "dashboard_base.html" %}

{% block content %}
<h1>Upload Track</h1>
{% if form.errors %}
<div class="alert alert-danger" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">Error:</span>
  There were some errors, please see below and correct.
</div>
{% endif %}
<form action="{% url "tracks.upload" %}" method="post" enctype="multipart/form-data">{% csrf_token %}
  <div class="form-group">
    <label for="{{ form.artist.id_for_label }}">Artist: </label>
    <input type="text" id="artist" name="artist" class="form-control" value="{{ form.artist.value|default:"" }}"/>
    <p class="help-block">{{ form.artist.errors }}</p>
  </div>
  <div class="form-group">
    <label for="{{ form.title.id_for_label }}">Title: </label>
    <input type="text" id="title" name="title" class="form-control" value="{{ form.title.value|default:"" }}" />
    <p class="help-block">{{ form.title.errors }}</p>
  </div>
  <div class="form-group">
    <label for="{{ form.track_file.id_for_label }}">Track File:</label>
    <p id="download-help-text" class="help-block">The track file (.mp3 files only)</p>
    <input type="file" id="id_track_file" name="track_file" value="{{ form.track_file.value|default:""}}" />
    <p class="help-block">{{ form.track_file.errors }}</p>
  </div>
  <input type="submit" value="Upload" class="btn btn-primary" />
</form>
<div>
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-9844785619338228"
     data-ad-slot="3698535390"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
{% endblock %}

tracks/templates/tracks/upload_success.html
{% extends "dashboard_base.html" %}

{% block content %}
<h1>Upload Succeeded</h1>
<div class="alert alert-success" role="alert">
Your track has been successfully uploaded. Link to the address below to trade follows for downloads.
</div>

<pre>http://follow2download.com/d/{{ uploaded_track.track_url_id }}</pre>
<div>
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-9844785619338228"
     data-ad-slot="3698535390"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-9844785619338228"
     data-ad-slot="2221802194"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-9844785619338228"
     data-ad-slot="9745068990"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
{% endblock %}